# Generated by Django 4.1.7 on 2023-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('codi', models.AutoField(primary_key=True, serialize=False, verbose_name='Codi')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('dataIni', models.DateTimeField(verbose_name='Data inici')),
                ('dataFi', models.DateTimeField(verbose_name='Data fi')),
                ('descripcio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcio')),
            ],
        ),
    ]
