# Generated by Django 4.1.7 on 2023-03-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Esdeveniment',
        ),
    ]
