# Generated by Django 4.1.7 on 2023-03-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0003_alter_esdeveniment_datafi_alter_esdeveniment_dataini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nom')),
                ('descripcio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripció')),
            ],
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='comarca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comarca'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email contacte'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='enllacos',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enllaços'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='entrades',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Entrades'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='espai',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Espai'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='horari',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Horari'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='imatges',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Imatges'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='municipi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipi'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='telefon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telèfon contacte'),
        ),
        migrations.AddField(
            model_name='esdeveniment',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL organitzador'),
        ),
        migrations.AlterField(
            model_name='esdeveniment',
            name='codi',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codi'),
        ),
        migrations.AlterField(
            model_name='esdeveniment',
            name='descripcio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripció'),
        ),
        migrations.CreateModel(
            name='TematicaEsdeveniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esdeveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esdeveniments.esdeveniment')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esdeveniments.tematica')),
            ],
        ),
    ]
