# Generated by Django 4.1.7 on 2023-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0005_alter_tematicaesdeveniment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='esdeveniment',
            name='tematiques',
            field=models.ManyToManyField(to='esdeveniments.tematica'),
        ),
        migrations.DeleteModel(
            name='TematicaEsdeveniment',
        ),
    ]
