# Generated by Django 4.1.7 on 2023-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0006_esdeveniment_tematiques_delete_tematicaesdeveniment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esdeveniment',
            name='tematiques',
            field=models.ManyToManyField(blank=True, null=True, to='esdeveniments.tematica'),
        ),
    ]
