# Generated by Django 4.1.7 on 2023-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0008_alter_tematica_options_alter_esdeveniment_tematiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esdeveniment',
            name='descripcio',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Descripció'),
        ),
    ]
