# Generated by Django 4.1.7 on 2023-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0009_alter_esdeveniment_descripcio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esdeveniment',
            name='codi',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Codi'),
        ),
    ]
