# Generated by Django 4.1.7 on 2023-04-02 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistenciaaesdeveniment',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data assistencia'),
        ),
    ]
