# Generated by Django 4.1.7 on 2023-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencies', '0002_assistenciaaesdeveniment_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssistenciaAEsdeveniment',
        ),
    ]
