# Generated by Django 4.1.7 on 2023-04-15 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esdeveniments', '0011_alter_esdeveniment_url'),
        ('assistencies', '0003_delete_assistenciaaesdeveniment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistenciaAEsdeveniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data assistencia')),
                ('esdeveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esdeveniments.esdeveniment', verbose_name='Codi esdeveniment')),
            ],
        ),
    ]
