# Generated by Django 4.1.7 on 2023-04-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistencies', '0004_initial'),
        ('usuaris', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistenciaaesdeveniment',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuaris.perfil', verbose_name='Id perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='assistenciaaesdeveniment',
            unique_together={('perfil', 'esdeveniment')},
        ),
    ]
