# Generated by Django 4.1.7 on 2023-04-25 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assistencies', '0006_alter_assistenciaaesdeveniment_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistenciaaesdeveniment',
            name='id',
        ),
        migrations.AddField(
            model_name='assistenciaaesdeveniment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
