# Generated by Django 4.1.7 on 2023-05-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0012_esdeveniment_organitzador'),
        ('assistencies', '0007_remove_assistenciaaesdeveniment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistenciaaesdeveniment',
            name='esdeveniment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistencies', to='esdeveniments.esdeveniment', verbose_name='Codi esdeveniment'),
        ),
    ]
