# Generated by Django 4.1.7 on 2023-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencies', '0008_alter_assistenciaaesdeveniment_esdeveniment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistenciaaesdeveniment',
            name='dataValidacio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data validació'),
        ),
    ]
