# Generated by Django 4.1.7 on 2023-04-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom')),
                ('dataCreacio', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('participants', models.ManyToManyField(related_name='xats', to='usuaris.perfil', verbose_name='Participants')),
            ],
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges', to='usuaris.perfil', verbose_name='Creador')),
                ('xat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges', to='xats.xat', verbose_name='Xat')),
            ],
        ),
    ]
