# Generated by Django 4.1.7 on 2023-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interessos', '0002_alter_interesentematica_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresEnEsdeveniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InteresEnTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
