# Generated by Django 4.1.7 on 2023-04-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interessos', '0003_initial'),
        ('esdeveniments', '0011_alter_esdeveniment_url'),
        ('usuaris', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesentematica',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuaris.perfil', verbose_name='Id perfil'),
        ),
        migrations.AddField(
            model_name='interesentematica',
            name='tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esdeveniments.tematica', verbose_name='Nom tematica'),
        ),
        migrations.AddField(
            model_name='interesenesdeveniment',
            name='esdeveniment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esdeveniments.esdeveniment', verbose_name='Codi esdeveniment'),
        ),
        migrations.AddField(
            model_name='interesenesdeveniment',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuaris.perfil', verbose_name='Id perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='interesentematica',
            unique_together={('perfil', 'tematica')},
        ),
        migrations.AlterUniqueTogether(
            name='interesenesdeveniment',
            unique_together={('perfil', 'esdeveniment')},
        ),
    ]
