# Generated by Django 4.1.7 on 2023-05-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esdeveniments', '0012_esdeveniment_organitzador'),
        ('interessos', '0005_alter_interesenesdeveniment_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesenesdeveniment',
            name='esdeveniment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessats', to='esdeveniments.esdeveniment', verbose_name='Codi esdeveniment'),
        ),
    ]
