# Generated by Django 4.1.7 on 2023-05-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0005_alter_perfil_imatge'),
        ('valoracions', '0002_alter_valoracio_options_valoracio_imatge_and_more'),
        ('interessos', '0006_alter_interesenesdeveniment_esdeveniment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresEnValoracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessos_valoracio', to='usuaris.perfil', verbose_name='Id perfil')),
                ('valoracio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valoracions.valoracio', verbose_name='Id valoració')),
            ],
            options={
                'unique_together': {('perfil', 'valoracio')},
            },
        ),
    ]
