# Generated by Django 4.1.7 on 2023-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencies', '0003_delete_assistenciaaesdeveniment'),
        ('interessos', '0002_alter_interesentematica_unique_together_and_more'),
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
