# Generated by Django 4.1.7 on 2023-04-15 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuaris', '0002_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organitzador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('descripcio', models.CharField(max_length=300, verbose_name='Descripció')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('telefon', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telèfon')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imatge de perfil')),
            ],
        ),
    ]
