# Generated by Django 4.1.7 on 2023-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Bio'),
        ),
    ]
