# Generated by Django 4.1.7 on 2023-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0004_perfil_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imatge',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Imatge de perfil'),
        ),
    ]
