# Generated by Django 4.1.7 on 2023-04-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuaris', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguits', to='usuaris.perfil', verbose_name='Perfil seguidor')),
                ('seguit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidors', to='usuaris.perfil', verbose_name='Perfil seguit')),
            ],
            options={
                'unique_together': {('seguidor', 'seguit')},
            },
        ),
    ]
