# Generated by Django 4.1.7 on 2023-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguiments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seguiment',
            constraint=models.CheckConstraint(check=models.Q(('seguidor', models.F('seguit')), _negated=True), name='no_es_pot_seguir_a_un_mateix'),
        ),
    ]
